In [2]:
!pip install html5lib

Requirement already satisfied: html5lib in c:\programdata\anaconda3\lib\site-packages (1.1)
Requirement already satisfied: webencodings in c:\programdata\anaconda3\lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: six>=1.9 in c:\programdata\anaconda3\lib\site-packages (from html5lib) (1.15.0)

In [3]:
import os
import numpy as np
import pandas as pd
import html5lib

In [4]:
br = pd.read_html('https://pt.wikipedia.org/wiki/Unidades_federativas_do_Brasil')

In [8]:
print(type(br))

<class 'list'>

In [12]:
u = br[1]

In [14]:
u.head()

,Bandeira,Unidade federativa,Abreviação,Sede de governo,Área (km²),População (2014),Densidade (2005),PIB (2015),(% total) (2015),PIB per capita (R$) (2015),IDH (2010),Alfabetização (2016),Mortalidade infantil (2016),Expectativa de vida (2016)
0,NaN,Acre,AC,Rio Branco,"164 122,2",795 145,430,13 622 000,2,"16 953,46",663,"86,9%","17,0‰","73,9 anos"
1,NaN,Alagoas,AL,Maceió,"27 767,7",3 327 551,10861,46 364 000,8,"13 877,53",631,"80,6%","19,5‰","71,6 anos"
2,NaN,Amapá,AP,Macapá,"142 814,6",756 500,416,13 861 000,2,"18 079,54",708,95%,"23,2‰","73,9 anos"
3,NaN,Amazonas,AM,Manaus,"1 570 745,7",3 893 763,205,86 560 000,14,"21 978,95",674,"93,1%","18,2‰","71,9 anos"
4,NaN,Bahia,BA,Salvador,"564 692,7",15 150 143,2446,245 025 000,41,"16 115,89",660,87%,"17,3‰","73,5 anos"

In [15]:
bcs = pd.read_html('https://pt.wikipedia.org/wiki/Lista_dos_maiores_bancos_do_Brasil')

In [19]:
b = bcs[2]

In [20]:
b

,Posição,Nome do banco,Cidade sede,Patrimônio líquido em R$ milhões,Data dos dados,País de origem
0,1,Banco Itaú Unibanco,São Paulo,144.3290,Dezembro de 2019,Brasil
1,2,Banco Bradesco,Osasco,138.9834,Dezembro de 2019,Brasil
2,3,Banco do Brasil,São Paulo,100.6455,Dezembro de 2019,Brasil
3,4,Caixa Econômica Federal,Brasília,80.7000,Dezembro de 2019,Brasil
4,5,Banco Santander Brasil,São Paulo,71.0191,Dezembro de 2019,Espanha
5,6,Sicoob,Brasília,23.4000,Dezembro de 2019,Brasil
6,7,Banco BTG Pactual,São Paulo,21.9837,Dezembro de 2019,Brasil
7,8,Banco Safra,São Paulo,12.1761,Dezembro de 2019,Brasil
8,9,Banco Votorantim,São Paulo,10.0271,Dezembro de 2019,Brasil
9,10,Banrisul,Porto Alegre,7.9096,Dezembro de 2019,Brasil
10,11,Citibank Brasil,São Paulo,5.9030,Dezembro de 2019,Estados Unidos
11,12,Banco do Nordeste,Fortaleza,5.4378,Dezembro de 2019,Brasil